### ISSUE TITLE
Can't run after following instructions

### ISSUE THREAD

**Issue by ahrnuld** [wimmelstein/mavenfx#1]
Followed all the steps. 

On step 5, javafx:run gives the following error:

[INFO] 
[INFO] --- javafx-maven-plugin:0.0.7:run (default-cli) @ mavenfx ---
[ERROR] Error executing Maven.
[ERROR] The specified user settings file does not exist: C:\Users\[username]\.m2\settings.xml

I do have an .m2 folder, but there is no settings.xml file in it.

**Comment by wimmelstein** [comment]
Unzip this file, and put it in the folder.
[settings.zip](https://github.com/wimmelstein/mavenfx/files/7189921/settings.zip)
..

**Comment by ahrnuld** [comment]
That works.
