### ISSUE TITLE
Login Button not appearing upon meeting criteria

### ISSUE THREAD

**Issue by REDitor** [wimmelstein/mavenfx#5]
In my branch Lesson3 LoginScreen (Improved) I cant seem to get the button to appear when the password meets all the criteria. Now i believe it has something to do with the changed Listener that is there and i dont know how i should use it. 
Could you have a look and see what i am doing wrong because I have absolutely no clue at this point?

**Comment by REDitor** [comment]
Also dont have the issues option in my own repo so thats why im here XD

**Comment by wimmelstein** [comment]
You are using a complicated regular expression. Yesterday during my workshop I told everybody that the prevailing rule is:
"I had a problem, and I tried to use regular expressions to solve it. Now I have two problems".
You could try an online regex checker (or use the one in IntelliJ as demonstrated in the workshop yesterday). My bet is that the regular expression is not matching your string.

**Comment by REDitor** [comment]
Okay thanks i must've missed that part. I'll check it again
